site_name: SimonScript.jsx
site_dir: '../SimonScript_Docs'
repo_url: https://github.com/Serifenlos/SimonScript
# edit_uri: edit/master/docs
edit_uri: ''
use_directory_urls: false
dev_addr: 'localhost:8000'


# theme: readthedocs
theme: 
    name: material
    custom_dir: custom_theme
#    features:
#        - navigation.tabs
    language: de
    palette:
        scheme: default
        primary: white
        accent: blue
    logo: assets/images/SS_logo.svg
    favicon: assets/images/favicon.png
    icon:
        repo: fontawesome/brands/github



extra_css: 
    - assets/stylesheets/extra.css
extra_javascript:
    - assets/javascripts/extra.js





nav:
    - Home: index.md
    - 'PhotoshopScripts':
        - 'Startschuss': 'PS_Scripts/startschuss.md'
        - 'Schlußschuss': 'PS_Scripts/schlussschuss.md'
    - 'functions':
        - 'basic': 'functions/basic.md'
        - 'dialog': 'functions/dialog.md'
        - 'layer': 'functions/layer.md'
        - 'loopFiles': 'functions/loopFiles.md'
        - 'LUT-burn': 'functions/LUT-burn.md'
        - 'LUT-dodge': 'functions/LUT-dodge.md'
        # - 'mb_Utils': 'functions/mb_Utils.md'
        - 'utils': 'functions/utils.md'
        - 'meta': 'functions/meta.md'
        - 'ready': 'functions/ready.md'
        - 'save': 'functions/save.md'
        - 'view': 'functions/view.md'
    - 'helpful':
        - 'snippets': 'helpful/snippets.md'
        - 'charID': 'helpful/charID.md'
      
  # - 'Assets':
  #   - 'assets': 'functions/zoom.md'


markdown_extensions:
    - smarty
    - admonition
    - meta
    - attr_list
    - pymdownx.betterem
    - pymdownx.superfences
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.highlight:
        use_pygments: true
        # linenums: true
        css_class: 'highlight'
        guess_lang: true
        noclasses: false
        linenums_style: pymdownx-inline
    - pymdownx.inlinehilite:
        css_class: 'highlight'
    - pymdownx.mark
    # - pymdownx.tabbed
    - pymdownx.details
    - markdown.extensions.md_in_html
    - pymdownx.magiclink
    - pymdownx.keys:
        key_map: {"commandxx": " ", "shiftxx": " "}


plugins:
    - search:
        separator: '[\s\-\.]+'
        lang:
            - en
            - de
        prebuild_index: true
    - localsearch
    - exclude:
        glob:
            - functions_helper/*
            - PS_Scripts_helper/*
            - '*.kit'
    # - mkdocs-nav-enhancements
  # - awesome-pages

# plugins:
#   - search:
#       separator: '[\s\-\.]+'
#       lang:
#         - en
#         - de
#         - ru
